[{
	"resource": "/dbt_project.yml",
	"owner": "dbt-lsp",
	"code": "1502",
	"severity": 8,
	"message": "[MacroSyntaxInvalid (dbt1502)]: Failed to parse macro SQL syntax error: non-keyword arg after keyword arg\n  --> ",
	"source": "dbt",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1,
	"origin": "extHost1"
}]